### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by idkjs** [Schniz/gpkg#4]
I dont see a binary mentioned in https://github.com/Schniz/fnm/issues/236#issuecomment-673571708. How do we build this?

**Comment by Schniz** [comment]
Hey! Currently AFK so can't give direct links. I haven't made any release yet but I'm using it every day. There's an artifact in the latest GitHub actions run that can be downloaded but I might release it this weekend and write a short installation guide because I'm not sure I did that

If you want to build it, you can do that by running `cargo build` in the root. The project is a standard Rust project

**Comment by idkjs** [comment]
Thank you, sir. Will try `cargo build`.

**Comment by idkjs** [comment]
You never released!

**Comment by Schniz** [comment]
haha sorry. I had COVID-19 but I'm recovered now and I'm catching up at work. I will release it soon, I hope! 😄
